project_id = "omwuyscprzexgmxgittp"

[functions.airtable-transactions]
verify_jwt = false

[functions.airtable-accounts]
verify_jwt = false

[functions.send-transaction]
verify_jwt = false

[functions.airtable-clients]
verify_jwt = false

[functions.webauthn]
verify_jwt = false

[functions.airtable-create-client]
verify_jwt = false