#!/usr/bin/env bash
# Generates docs/print-bridge-bilingual/print-bridge-v6.4.0-bilingual.js
# from the untouched v6.3.7-clean bridge + bilingual-layer.js.
# The clean file is only READ, never modified.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/docs/print-bridge-installer/print-bridge-v6.3.7-clean.js"
LAYER="$ROOT/docs/print-bridge-bilingual/bilingual-layer.js"
OUT="$ROOT/docs/print-bridge-bilingual/print-bridge-v6.4.0-bilingual.js"

python3 - "$SRC" "$LAYER" "$OUT" <<'PY'
import sys, re
src, layer, out = sys.argv[1:4]
s = open(src, encoding='utf-8').read()
for fn in ('renderReceiptSVG', 'renderKitchenSVG', 'renderShiftSVG'):
    decl = f'function {fn}('
    assert s.count(decl) == 1, fn
    s = s.replace(decl, f'function {fn}_ar(')
v = re.search(r"const BRIDGE_VERSION = '([^']+)';", s)
assert v
s = s.replace(v.group(0), "const BRIDGE_VERSION = '6.4.0-bilingual';")
anchor = "    features: BRIDGE_FEATURES,\n"
assert s.count(anchor) == 1
s = s.replace(anchor, anchor + "    capabilities: ['lang-en'],\n")
s = "// AUTO-GENERATED by scripts/build-bilingual-bridge.sh — do not edit.\n" + s + "\n" + open(layer, encoding='utf-8').read()
open(out, 'w', encoding='utf-8').write(s)
PY
node --check "$OUT"
echo "Built $OUT"
