// Shared formatting helpers for reports
export const fmtNum = (n: number) => n.toLocaleString("en", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
export const fmtAmt = (n: number) => `₪${fmtNum(Math.abs(n))}`;
export const fmtAmtCell = (v: any) => v != null && v !== 0 ? `₪${Math.abs(Number(v)).toLocaleString("en", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : "—";

export const reportConfigs: Record<string, { title: string; description: string }> = {
  "ar-aging": { title: "أعمار الذمم المدينة", description: "أرصدة الزبائن المستحقة مصنفة حسب العمر" },
  "ap-aging": { title: "أعمار الذمم الدائنة", description: "أرصدة الموردين المستحقة مصنفة حسب العمر" },
  "cash-flow": { title: "حركة النقد حسب النشاط", description: "حركة النقد المباشرة مصنفة: تشغيلي / استثماري / تمويلي / غير مصنف / تحويلات داخلية" },
  "daily-sales": { title: "المبيعات اليومية", description: "ملخص المبيعات يوماً بيوم" },
  "sales-returns": { title: "مرتجعات المبيعات", description: "جميع مردودات المبيعات وإشعارات الدائن" },
  "sales-by-product": { title: "المبيعات حسب الصنف", description: "كمية وقيمة المبيعات لكل منتج" },
  "sales-performance": { title: "أداء المبيعات", description: "مؤشرات الأداء ونسبة النمو" },
  "purchase-returns": { title: "مرتجعات المشتريات", description: "مردودات الشراء وإشعارات المدين" },
  "supplier-comparison": { title: "مقارنة أسعار الموردين", description: "مقارنة أسعار نفس الصنف بين الموردين" },
  "dead-stock": { title: "أصناف راكدة", description: "منتجات بدون حركة لأكثر من 90 يوم" },
  "product-profitability": { title: "ربحية الأصناف", description: "هامش الربح لكل منتج" },
  "foreign-balances": { title: "أرصدة العملات الأجنبية", description: "الأرصدة بالعملة الأجنبية ومعادلها بالشيكل" },
  "exchange-gain-loss": { title: "أرباح وخسائر العملة", description: "فروقات محققة وغير محققة" },
  "order-performance": { title: "أداء المنتجات", description: "الأكثر طلباً والأكثر ربحية" },
  "financial-kpi": { title: "المؤشرات المالية", description: "نسب التداول والربحية والدوران" },
  "month-comparison": { title: "المقارنة الشهرية", description: "مقارنة الإيرادات والمصروفات شهر بشهر" },
  "cash-movement": { title: "حركة الصندوق", description: "جميع حركات النقد الوارد والصادر من الصندوق" },
  "bank-movement": { title: "حركة البنوك", description: "حركات الحسابات البنكية" },
  "cheques": { title: "تقرير الشيكات", description: "شيكات واردة وصادرة ومستحقة مع الحالة" },
  "total-sales": { title: "المبيعات الإجمالية", description: "إجمالي المبيعات حسب الفترة" },
  "invoice-register": { title: "سجل الفواتير", description: "جميع فواتير البيع مع حالة الدفع" },
  "by-customer": { title: "المبيعات حسب الزبون", description: "تحليل مبيعات كل زبون" },
  "collections": { title: "التحصيلات", description: "المبالغ المحصلة من الزبائن" },
  "total-purchases": { title: "المشتريات الإجمالية", description: "إجمالي المشتريات حسب الفترة" },
  "purchase-invoice-register": { title: "فواتير المشتريات", description: "سجل فواتير الشراء" },
  "by-supplier": { title: "المشتريات حسب المورد", description: "تحليل مشتريات كل مورد" },
  "supplier-payments": { title: "المدفوعات للموردين", description: "جميع المبالغ المدفوعة" },
  "inventory-valuation": { title: "جرد وتقييم المخزون (لحظي)", description: "كميات وقيم المخزون كما هي الآن — التكلفة = سعر الشراء الحالي للمنتج (products.buy_price)" },
  "stock-movement": { title: "حركة المخزون", description: "حركات الوارد والصادر" },
  "purchases-by-product": { title: "المشتريات حسب الصنف", description: "كميات وقيم المشتريات لكل منتج (صافي بعد المرتجعات)" },
  "inventory-reconciliation": { title: "تطابق المخزون", description: "مقارنة كمية المنتج الحية مع مجموع حركات المخزون" },
  "product-card": { title: "بطاقة الصنف / كشف حركة المنتج", description: "حركات كل صنف بالترتيب الزمني مع الرصيد المتحرك" },
  "below-reorder": { title: "أصناف تحت الحد الأدنى", description: "منتجات تحتاج إعادة طلب" },
  "employee-directory": { title: "بيانات الموظفين", description: "دليل شامل لجميع الموظفين" },
  "employee-withdrawals": { title: "مسحوبات الموظفين", description: "تفصيل مسحوبات كل موظف حسب نوع العملية" },
  "asset-register": { title: "سجل الأصول الثابتة", description: "جميع الأصول مع القيمة الدفترية" },
  "monthly-depreciation": { title: "الاستهلاك الشهري", description: "قيمة الاستهلاك المحسوبة لكل أصل" },
  "depreciation-schedule": { title: "جدول الاستهلاك التفصيلي", description: "جدول زمني كامل لاستهلاك كل أصل" },
  "fully-depreciated": { title: "أصول مستهلكة بالكامل", description: "أصول وصلت لنهاية عمرها الإنتاجي" },
  "asset-disposal": { title: "أرباح وخسائر بيع الأصول", description: "عمليات الاستبعاد والبيع" },
  "assets-by-location": { title: "الأصول حسب الموقع", description: "تجميع حسب الفرع والقسم" },
  "exchange-rates": { title: "أسعار الصرف", description: "تاريخ أسعار الصرف" },
  "currency-conversions": { title: "تحويلات العملات", description: "عمليات تحويل العملات" },
  "all-orders": { title: "تقرير الطلبات", description: "جميع الطلبات مع حالتها" },
  "pos-daily-sales": { title: "مبيعات نقطة البيع اليومية", description: "مبيعات POS حسب الكاشير" },
  "pos-sales-by-category": { title: "مبيعات حسب الفئة والصنف", description: "تحليل المبيعات حسب فئة المنتج" },
  "pos-period-comparison": { title: "مقارنة زمنية للمبيعات", description: "مقارنة يومية / أسبوعية / شهرية" },
  "pos-invoice-register": { title: "كشف فواتير POS", description: "جميع فواتير نقطة البيع مع التفاصيل" },
  "pos-pending-orders": { title: "فواتير معلقة", description: "الطلبات المفتوحة غير المكتملة" },
  "pos-invoice-timing": { title: "كشف أوقات الفواتير", description: "مدة الخدمة لكل فاتورة من الفتح للإغلاق" },
  "pos-shift-open-close": { title: "تقرير فتح/إغلاق الصندوق", description: "أوقات فتح وإغلاق الورديات" },
  "pos-payment-methods": { title: "طرق الدفع", description: "توزيع المبيعات حسب طريقة الدفع" },
  "pos-credit-sales": { title: "بطاقات الائتمان والمديونيات", description: "المبيعات الآجلة ومديونيات العملاء" },
  "pos-product-movement": { title: "حركة أصناف POS", description: "الكميات المباعة والمرتجعة لكل صنف" },
  "pos-category-totals": { title: "مجاميع حركات الأصناف", description: "إجماليات المبيعات حسب الفئة" },
  "pos-cash-reconciliation": { title: "تسوية الصندوق", description: "المتوقع مقابل الفعلي" },
  "pos-cashier-performance": { title: "أداء الكاشيرين", description: "أداء كل كاشير بالأرقام" },
  "pos-cancelled": { title: "الفواتير الملغية", description: "الفواتير الملغاة مع الأسباب" },
  "pos-peak-hours": { title: "ساعات الذروة", description: "توزيع المبيعات حسب الساعة" },
  "ar-aging-detail": { title: "تعمير ذمم الزبائن", description: "تصنيف جميع الذمم المستحقة من الزبائن حسب عمر الدين" },
  "dso-report": { title: "أيام التحصيل والأداء (DSO)", description: "متوسط أيام التحصيل لكل زبون مع التصنيف" },
  "checks-receivable": { title: "تقرير الشيكات الواردة", description: "شيكات الزبائن مصنفة حسب الحالة والاستحقاق" },
  "customer-profitability": { title: "ربحية الزبائن", description: "المبيعات والهوامش لكل زبون" },
  "customer-statement-all": { title: "كشف حساب موحد للزبائن", description: "كشف حساب شامل لجميع الزبائن" },
  "ap-aging-detail": { title: "تعمير ذمم الموردين", description: "المبالغ المستحقة للموردين حسب عمر الدين" },
  "dpo-report": { title: "أيام سداد الموردين (DPO)", description: "متوسط أيام السداد لكل مورد" },
  "checks-payable": { title: "تقرير الشيكات الصادرة", description: "شيكات الموردين مع تواريخ الاستحقاق" },
  "supplier-purchase-analysis": { title: "تحليل المشتريات والموردين", description: "حجم المشتريات من كل مورد" },
  "supplier-statement-all": { title: "كشف حساب موحد للموردين", description: "كشف حساب شامل لجميع الموردين" },
  "invoice-lifecycle": { title: "دورة حياة الفاتورة", description: "تتبع كل فاتورة من الإنشاء حتى الإغلاق" },
  "dso-detailed": { title: "متوسط أيام التحصيل (DSO) المتقدم", description: "كم يوماً يستغرق كل زبون للسداد" },
  "ar-aging-advanced": { title: "تعمير الذمم المدينة المتقدم", description: "توزيع الذمم على شرائح زمنية مع تفصيل كل فاتورة" },
  "collection-efficiency": { title: "كفاءة التحصيل", description: "نسبة الفواتير المسدّدة في موعدها وتطورها شهرياً" },
  "payment-allocation": { title: "سجل المدفوعات المرتبطة", description: "كل سند قبض مرتبط بأي فاتورة وبأي مبلغ" },
  "unpaid-invoices": { title: "الفواتير المستحقة (Outstanding)", description: "فواتير المبيعات النشطة التي لها رصيد متبقٍ > 0" },
  "vat-reconciliation": { title: "تطابق ضريبة القيمة المضافة", description: "مقارنة سجل الضريبة (tax_ledger) مع حركة حسابات ضريبة المبيعات والمدخلات في الأستاذ العام شهرياً" },
  "pos-gl-reconciliation": { title: "تطابق نقطة البيع مع الأستاذ العام", description: "مقارنة يومية بين فواتير POS وقيود الأستاذ العام: الإيرادات / الضريبة / النقد / البنك" },
};
