
ALTER TABLE public.accounts
  ADD COLUMN IF NOT EXISTS description_ar TEXT,
  ADD COLUMN IF NOT EXISTS sub_group_label VARCHAR(100),
  ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_system_protected BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS system_role VARCHAR(50);
