ALTER TABLE public.qamar_orders
ADD COLUMN IF NOT EXISTS deposit_amount NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS remaining_amount NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS deposit_paid_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS remaining_paid_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS payment JSONB DEFAULT '{}'::jsonb;