ALTER TABLE products
  ADD COLUMN IF NOT EXISTS barcode TEXT,
  ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_sold BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_purchased BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_pos_product BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS sales_account_code TEXT,
  ADD COLUMN IF NOT EXISTS purchase_account_code TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS terms TEXT;