
ALTER TABLE public.company_settings
  ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS onboarding_step INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS business_type VARCHAR(50),
  ADD COLUMN IF NOT EXISTS has_employees BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS employee_count_range VARCHAR(20),
  ADD COLUMN IF NOT EXISTS has_pos BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS pos_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS inventory_method VARCHAR(20) DEFAULT 'weighted_average',
  ADD COLUMN IF NOT EXISTS onboarding_skipped BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS onboarding_completed_at TIMESTAMPTZ;
